### ISSUE TITLE
New Word in Glossary: Path

### ISSUE THREAD

**Issue by nkelber** [DHRI-Curriculum/glossary#12]
I'm still a little confused as to what a "path" is and how to change it. Can you add it to the glossary?

**Comment by kallewesterling** [comment]
Hi @nkelber! I understand this was entered quite a long time ago here in the suggestions but as we're trying to wrap up the curriculum for our GitBook, I'm returning to the glossary suggestions now. I just wanted to clarify: Do you remember if the `path` you're referring to in the question refers to the path of the command line workshop? I'm going to label this glossary entry this way, but feel free to let me know/change it if you were referring to any other form of `path` (as in the paths used in vector graphics for example).

**Comment by nkelber** [comment]
That's right, Kalle. I was referring to the path in the command line
workshop. Basically, the filepath that allows the command line to execute
the proper program when it is typed into the command line interface.

**Comment by kallewesterling** [comment]
Awesome - thanks for the clarification!
