### ISSUE TITLE
add glossaries for databases & remaining workshops

### ISSUE THREAD

**Issue by kchatlosh** [DHRI-Curriculum/glossary#30]
it would be great to have a glossary for each workshop that we teach!

especially databases because it's one of the core sessions taught to all (at dhri or dri) -- and it'd be great to include a list of sql commands as well as a glossary of key terms that relate to using sql (e.g. "field")

and then it'd be great to add glossaries for the remaining elective workshops too if/when time:
omeka
machine learning
mapping
html css

**Comment by kallewesterling** [comment]
Yup, this is important & something we're adding to the publishable curriculum.

I have also created a separate repo that is currently out for review from everyone: See #28

**Comment by kallewesterling** [comment]
Also see the "Add glossary category" issues open here (#10, #14)
